name: Setup / Installation Issue
description: Report a problem with setting up or installing the project
labels: ['setup', 'installation', 'bug']
body:
  - type: markdown
    attributes:
      value: |
        Use este template para relatar problemas encontrados durante a configuração ou instalação do projeto. 
        Descreva o problema de forma detalhada e forneça todas as informações necessárias para que possamos reproduzir e resolver o problema rapidamente.

  - type: input
    attributes:
      label: Sistema Operacional e Versão
      description: Qual o sistema operacional e a versão que você está usando?
      placeholder: 'Exemplo: Windows 10, Ubuntu 20.04'
    validations:
      required: true

  - type: input
    attributes:
      label: Versão do Projeto
      description: Qual a versão do projeto que você está tentando instalar?
      placeholder: 'Exemplo: v1.2.3'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Descrição Detalhada do Problema
      description: Descreva o problema que você encontrou com o máximo de detalhes possível.
      placeholder: 'Inclua qualquer mensagem de erro específica, comportamento inesperado e passos para reproduzir o problema.'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Passos para Reproduzir
      description: Forneça uma lista passo a passo de como reproduzir o problema.
      placeholder: |
        1. Baixe a versão 'x' do projeto do GitHub.
        2. Execute o comando 'xyz' no terminal.
        3. Observe o erro no passo 3.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Tentativas de Solução
      description: Descreva qualquer tentativa que você fez para resolver o problema por conta própria.
      placeholder: 'Descreva qualquer passo que você tenha tomado para tentar solucionar o problema antes de submeter esta issue.'

  - type: markdown
    attributes:
      value: |
        ## Informações Adicionais
        Se possível, inclua capturas de tela, logs de erro ou qualquer outro recurso que possa ajudar a diagnosticar o problema.
