name: User Story
description: Propose a new user story for the project
labels: ['user story']
body:
  - type: markdown
    attributes:
      value: |
        Este template é para propor novas user stories para o projeto. User stories ajudam a equipe a entender as necessidades dos usuários de forma clara e concisa.
        
        Antes de submeter uma nova user story, por favor verifique se uma história similar já existe.

  - type: textarea
    attributes:
      label: Título da User Story
      description: Escreva um título breve e descritivo para a user story.
      placeholder: 'Como [perfil do usuário], quero [funcionalidade] para que [benefício].'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Descrição Detalhada
      description: Forneça uma descrição mais detalhada da user story, incluindo qualquer contexto ou justificativa adicional.
      placeholder: 'Detalhe aqui os comportamentos esperados, condições e qualquer regra de negócio relevante para a user story.'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Critérios de Aceitação
      description: Liste os critérios específicos que devem ser atendidos para que a user story seja considerada completa.
      placeholder: |
        1. O sistema deve [descrição do comportamento].
        2. A funcionalidade deve ser acessível em [especificar dispositivos/plataformas].
        3. A interface deve seguir [especificações de design ou acessibilidade].
    validations:
      required: true

  - type: textarea
    attributes:
      label: Benefícios
      description: Descreva os benefícios desta user story para os usuários finais e para o projeto.
      placeholder: 'Esta user story vai melhorar [aspecto do projeto] porque [razão].'
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Prioridade
      options:
        - label: 'Baixa'
        - label: 'Média'
        - label: 'Alta'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Anexos e Referências
        Adicione quaisquer documentos de referência, mockups, diagramas ou outros anexos que possam ajudar a equipe a entender melhor esta user story.
