import type { Metadata } from 'next'
import { Space_Grotesk as spaceGrotesk } from 'next/font/google'
import { ThemeProvider } from '../providers/ThemeProvider'

const inter = spaceGrotesk({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body className={inter.className}>{children}</body>
      </ThemeProvider>
    </html>
  )
}
