#!/usr/bin/env sh

# Load Husky
. "$(dirname -- "$0")/_/husky.sh"

# Extract commit message
COMMIT_MESSAGE=$(cat "$1")

# Check if it's a merge commit
IS_MERGE=$(echo "$COMMIT_MESSAGE" | grep -qE '^Merge ' && echo true || echo false)

# Extract ticket numbers from commit message
HAS_TICKETS=$(echo "$COMMIT_MESSAGE" | grep -qE '\[PORT-[0-9]+\]' && echo true || echo false)

# Skip verification if it's a merge commit
if [ "$IS_MERGE" = true ]; then
  echo "ℹ️ Merge commit detected, skipping ticket verification."
  npx --no -- commitlint --edit "${1}"
  exit 0
fi

# Check if there is at least one ticket in the commit message
if [ "$HAS_TICKETS" = false ]; then
  printf "❌ Error: The commit message must include at least one ticket (PORT).\n"
  exit 1
fi

# Run commitlint
npx --no -- commitlint --edit "${1}"
