#!/usr/bin/env sh

# Load Husky
. "$(dirname -- "$0")/_/husky.sh"

# Extract ticket numbers from commit message
COMMIT_MESSAGE=$(cat "$1")
HAS_TICKETS=$( echo "$COMMIT_MESSAGE" | grep -qE '\[PORT-[0-9]+\]' && echo true || echo false )

# Check if there is at least one ticket in the commit message
if [ "$HAS_TICKETS" = false ]; then
  printf "❌ Error: The commit message must include at least one ticket (PORT).\n"
  exit 1
fi

# Run commitlint
npx --no -- commitlint --edit ${1}
